"""
Render analysis-only contact sheets for the pixel-passing pairs that the
upstream 8-band blocking never enumerated.

This script exists because a numerical similarity score is not evidence of
duplicate content. Every pair must be looked at.

Each sheet shows, left to right:
    image A | image B | absolute difference, contrast-stretched

Source images are opened read-only and are never written, resized in place,
or modified. Everything is written under
`experiments/dataset/normalized_rdd2022_india/group_analysis/`.

Usage:
    python scripts/analysis/render_missed_pair_contact_sheets.py
"""
from pathlib import Path
from typing import Any, Dict
import json
import sys

import numpy as np
from PIL import Image, ImageDraw

REPO_ROOT = Path(__file__).resolve().parent.parent
NORMALIZED_DIR = REPO_ROOT / "experiments" / "dataset" / "normalized_rdd2022_india"
GROUP_ANALYSIS_DIR = NORMALIZED_DIR / "group_analysis"
IMAGES_DIR = NORMALIZED_DIR / "train" / "images"
PAIRS_JSON = GROUP_ANALYSIS_DIR / "missed_pixel_pairs.json"
OUT_DIR = GROUP_ANALYSIS_DIR / "missed_pair_contact_sheets"

TILE = 300
LABEL_H = 74
GAP = 8


def stretched_diff(a: Image.Image, b: Image.Image) -> Image.Image:
    """
    Absolute difference of the two images, contrast-stretched.

    The raw absolute difference of two natural images is usually almost black,
    so the 1st..99th percentile is mapped to 0..255. A pair that is a genuine
    duplicate therefore shows only faint residue, while a pair that merely
    shares a road layout still shows a visible scene ghost. Stretching changes
    only the DISPLAY, never the measured statistics.
    """
    aa = np.asarray(a.convert("L"), dtype=np.float64)
    bb = np.asarray(b.convert("L"), dtype=np.float64)
    if aa.shape != bb.shape:
        return Image.new("L", a.size, 0)
    d = np.abs(aa - bb)
    lo, hi = np.percentile(d, 1.0), np.percentile(d, 99.0)
    if hi <= lo:
        stretched = np.zeros_like(d)
    else:
        stretched = np.clip((d - lo) / (hi - lo) * 255.0, 0, 255)
    return Image.fromarray(stretched.astype(np.uint8)).convert("RGB")


def render_sheet(pair: Dict, out_path: Path) -> None:
    ia = Image.open(IMAGES_DIR / f"{pair['a']}.jpg").convert("RGB")
    ib = Image.open(IMAGES_DIR / f"{pair['b']}.jpg").convert("RGB")
    diff = stretched_diff(ia, ib)
    tiles = [("A", ia), ("B", ib), ("|A-B| stretched", diff)]
    width = TILE * 3 + GAP * 2
    height = LABEL_H + TILE
    sheet = Image.new("RGB", (width, height), (18, 18, 18))
    draw = ImageDraw.Draw(sheet)
    lines = [
        f"{pair['a']}  <->  {pair['b']}     (pair {pair['rank']} of {pair['total']})",
        f"dHash={pair['dhash_distance']}  corr={pair['pixel_corr']:.4f}  "
        f"MAD={pair['pixel_mad']:.4f}  size={pair['width']}x{pair['height']}",
        f"blind-spot bands: {pair['differing_bands']}  "
        f"differing bits={pair['differing_bit_positions']}",
    ]
    for i, t in enumerate(lines):
        draw.text((6, 4 + i * 13), t, fill=(230, 230, 230))
    for i, (label, im) in enumerate(tiles):
        x = i * (TILE + GAP)
        sheet.paste(im.resize((TILE, TILE), Image.Resampling.LANCZOS), (x, LABEL_H))
        draw.rectangle([x, LABEL_H, x + TILE - 1, LABEL_H + TILE - 1], outline=(90, 90, 90))
        draw.text((x + 4, LABEL_H - 13), label, fill=(200, 200, 120))
    sheet.save(out_path, format="PNG", optimize=True)
    ia.close()
    ib.close()
    diff.close()


def main() -> int:
    if not PAIRS_JSON.exists():
        print(f"ERROR: {PAIRS_JSON} not found. Run analysis/audit_h11_evidence_scope.py first.")
        return 1
    payload = json.loads(PAIRS_JSON.read_text(encoding="utf-8"))
    pairs = payload["pairs"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Rendering {len(pairs)} contact sheets to {OUT_DIR}")
    for p in pairs:
        name = f"pair_{p['rank']:02d}_{p['a']}__{p['b']}.png"
        render_sheet(p, OUT_DIR / name)
        print(f"  {name}")
    index = OUT_DIR / "README.md"
    index.write_text(
        "# Analysis artifact: missed-pair contact sheets\n\n"
        "**Status**: ANALYSIS ONLY. No split created, no image assigned, no source\n"
        "image modified. These are derived visualisations of the six pixel-passing\n"
        "pairs that the upstream 8-band blocking never enumerated.\n\n"
        "Generated by `analysis/render_missed_pair_contact_sheets.py` from\n"
        "`missed_pixel_pairs.json`.\n\n"
        "Each sheet shows image A, image B, and the contrast-stretched absolute\n"
        "difference. The stretch affects display only; every measured statistic in\n"
        "`missed_pixel_pairs.json` is computed on the untouched 64x64 grayscale\n"
        "signature.\n\n"
        "These sheets are evidence for human review. They do not establish that\n"
        "any pair is a duplicate, and they do not establish common capture.\n",
        encoding="utf-8",
    )
    print(f"  README.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
